# Generated by Django 5.2.9 on 2026-01-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_business_type_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstatemodel',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='contact.contact'),
        ),
    ]
