# Generated by Django 5.2.9 on 2026-01-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_conversationstatemodel_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInboundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('provider_message_id', models.CharField(max_length=128)),
                ('whatsapp_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('raw_payload', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('provider', 'provider_message_id')},
            },
        ),
    ]
