# Generated by Django 5.2.9 on 2026-01-03 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_messageinboundmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReorderProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED')], default='ACTIVE', max_length=16)),
                ('cadence_days', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_weekdays', models.JSONField(blank=True, null=True)),
                ('next_reorder_date', models.DateField(blank=True, null=True)),
                ('default_list_code', models.CharField(default='kiosk_base', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_profile', to='contact.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactFactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value_json', models.JSONField()),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('USER', 'USER'), ('SYSTEM', 'SYSTEM'), ('AI', 'AI'), ('IMPORT', 'IMPORT')], max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='contact.contact')),
            ],
            options={
                'unique_together': {('contact', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ContactSkuStatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=128)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('qty_total', models.PositiveIntegerField(default=0)),
                ('qty_last', models.PositiveIntegerField(default=0)),
                ('qty_avg', models.FloatField(default=0.0)),
                ('first_ordered_at', models.DateTimeField(blank=True, null=True)),
                ('last_ordered_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_stats', to='contact.contact')),
            ],
            options={
                'unique_together': {('contact', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ContactTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('confidence', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='contact.contact')),
            ],
            options={
                'unique_together': {('contact', 'tag')},
            },
        ),
    ]
