# Generated by Django 5.2.9 on 2026-01-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contactexternalidentitymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactreorderprofilemodel',
            name='postpone_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contactreorderprofilemodel',
            name='postpone_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactreorderprofilemodel',
            name='postpone_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactreorderprofilemodel',
            name='postpone_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPLIED', 'APPLIED'), ('REJECTED', 'REJECTED')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='contactreorderprofilemodel',
            name='postpone_until_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactreorderprofilemodel',
            name='postpone_window',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
