# Generated by Django 5.2.9 on 2026-01-02 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '__first__'),
        ('inventory', '0006_contact_remove_stockmovement_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='contact.contact'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
