# Generated by Django 5.2.9 on 2026-01-02 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockmovement_contact_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductListItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_qty', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='inventory.product')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.productlistmodel')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product_list', 'product'), name='uniq_product_in_list'), models.CheckConstraint(condition=models.Q(('default_qty__gt', 0)), name='check_default_qty_gt_0')],
            },
        ),
    ]
