# Generated by Django 5.2.9 on 2025-12-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='low_stock_threshold',
            new_name='stock_minimum',
        ),
    ]
