# Generated by Django 5.2.9 on 2025-12-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_low_stock_threshold_product_stock_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'entry'), ('exit', 'exit'), ('adjust', 'adjust')], max_length=16),
        ),
    ]
