# Generated by Django 5.2.9 on 2025-12-24 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'entry'), ('exit', 'exit'), ('adjust_count', 'adjust_count'), ('adjust_delta', 'adjust_delta')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['entry', 'exit', 'adjust_count', 'adjust_delta'])), name='movement_type_valid_choices'),
        ),
    ]
