"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

def _env(*names):
    for n in names:
        v = os.getenv(n)
        if v:
            return v
    return None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3vkfdzlwl95%mf5zd+_$_^jqbx%l1t#i1$r*d=9x1a1s-sb0=r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

_default_hosts = ['localhost', '127.0.0.1']
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', ','.join(_default_hosts)).split(',') if h.strip()]
CSRF_TRUSTED_ORIGINS = [
    *[f"https://{h.lstrip('.')}" for h in ALLOWED_HOSTS if not h.startswith('.')],
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    'panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'panel' / 'src' / 'web' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_pg_host = _env('PGHOST', 'almacenamiento_PGHOST')
_pg_user = _env('PGUSER', 'almacenamiento_PGUSER')
_pg_password = _env('PGPASSWORD', 'almacenamiento_PGPASSWORD')
_pg_db = _env('PGDATABASE', 'almacenamiento_PGDATABASE')
_pg_port = _env('PGPORT', 'almacenamiento_PGPORT') or '5432'
_pg_sslmode = _env('PGSSLMODE', 'almacenamiento_PGSSLMODE')
_aws_region = _env('AWS_REGION', 'almacenamiento_AWS_REGION')

# Try AWS IAM auth token if password not provided
if not _pg_password and _pg_host and _pg_user and _aws_region:
    try:
        import boto3
        rds = boto3.client('rds', region_name=_aws_region)
        _pg_password = rds.generate_db_auth_token(DBHostname=_pg_host, Port=int(_pg_port), DBUsername=_pg_user)
    except Exception:
        _pg_password = None
_pg_url = None
if _pg_host and _pg_user and _pg_db and _pg_password:
    _pg_url = f"postgres://{_pg_user}:{_pg_password}@{_pg_host}:{_pg_port}/{_pg_db}"
    if _pg_sslmode:
        _pg_url += f"?sslmode={_pg_sslmode}"

_DB_URL = _env('DATABASE_URL', 'POSTGRES_URL', 'POSTGRES_PRISMA_URL') or _pg_url

DATABASES = {
    'default': (
        dj_database_url.parse(_DB_URL, conn_max_age=600)
        if _DB_URL
        else dj_database_url.config(default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'), conn_max_age=0)
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = "/panel/login/"
LOGIN_REDIRECT_URL = "/panel/"
LOGOUT_REDIRECT_URL = "/panel/login/"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'inventory.movements': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
